questions:
  path: /
  defaults: { _controller: NeonExchangeBundle:Questions:index }

neon_exchange:
  resource: "@NeonExchangeBundle/Controller/"
  type: annotation
  prefix: /
  
questions_by_tag:
  path: /questions/{tag}
  defaults: { _controller: NeonExchangeBundle:Questions:index }